import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/search?q=npx+playwright+codegen&oq=npx+playwright+codegen&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDExMjhqMGoyqAIAsAIB&sourceid=chrome&ie=UTF-8');
  await page.goto('about:blank');
  await page.goto('https://new-stage2-deployer.getglobalgroup.com/login');
  await page.getByPlaceholder('User Name').click();
  await page.getByPlaceholder('User Name').click();
  await page.getByPlaceholder('User Name').fill('124_employee@mailinator.com');
  await page.getByPlaceholder('Password', { exact: true }).click();
  await page.getByPlaceholder('Password', { exact: true }).fill('Pass@123');
  await page.getByPlaceholder('Password', { exact: true }).press('Enter');
  await page.getByRole('button').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' Recruiter' }).click();
  const page1 = await page1Promise;
  await page1.goto('https://new-stage2-recruiter.getglobalgroup.com/');
  await page1.goto('https://new-stage2-recruiter.getglobalgroup.com/dashboard');
  await page1.goto('https://new-stage2-recruiter.getglobalgroup.com/job-openings/0d7fbc2713b286ee45ee42c5ed0ee124?q=TestUser_571%20Last_594');
  await page1.getByLabel('more').click();
  await page1.getByRole('menuitem', { name: 'Complete' }).click();
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('html').click();
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('html').click();
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('#tinymce').fill('Testing');
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('html').click();
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('#tinymce').fill('Testing   ');
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().getByText('Testing').click();
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('#tinymce').fill('Testing   we');
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('html').click();
  await page1.getByLabel('Subject').click();
  await page1.getByLabel('Subject').fill('test');
  await page1.getByLabel('Communication Channel').locator('span').click();
  await page1.getByRole('option', { name: 'Chat' }).click();
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().locator('html').click();
  await page1.locator('iframe[title="Rich Text Area\\. Press ALT-F9 for menu\\. Press ALT-F10 for toolbar\\. Press ALT-0 for help"]').contentFrame().getByText('Testing we').click();
  await page1.getByRole('button', { name: 'VALIDATE & COMPLETE' }).click();
});